//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36365
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_OneProject
{
    using System;
    using HP.ST.Fwk.RunTimeFWK;
    
    
    public partial class Test_One
    {
        
        private string _value;
        
        private string _name;
        
        //  InputProperties Section
        [Report()]
        public virtual string value
        {
            get
            {
                return this._value;
            }
            set
            {
                this._value = value;
            }
        }
        
        //  GeneralProperties Section
        [Report()]
        public virtual string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
    }
}
