
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel.Activation;
using System.ServiceModel.Web;
using System.Text;
using System.ServiceModel;
using System.IO;

namespace Test_OneProject
{
    [ServiceContract]
    [ServiceBehavior(InstanceContextMode = InstanceContextMode.Single,
                 ConcurrencyMode = ConcurrencyMode.Single, IncludeExceptionDetailInFaults = true)]
    [AspNetCompatibilityRequirements(RequirementsMode = AspNetCompatibilityRequirementsMode.Allowed)]
    public partial class Test_One 
    {
        [OperationContract]
        [WebInvoke(UriTemplate = "LogDebug", BodyStyle = WebMessageBodyStyle.Bare, Method = "POST")]
        public void ServiceLogDebug(Stream content)
        {
            LogDebug(GetStringFromStream(content));
        }

        [OperationContract]
        [WebInvoke(UriTemplate = "LogError", BodyStyle = WebMessageBodyStyle.Bare, Method = "POST")]
        public void ServiceLogError(Stream content)
        {
            LogError(GetStringFromStream(content));
        }

    
        [OperationContract]
        [WebInvoke(UriTemplate = "LogInfo", BodyStyle = WebMessageBodyStyle.Bare, Method = "POST")]
        public void ServiceLogInfo(Stream content)
        {
            LogInfo(GetStringFromStream(content));
        }

        [OperationContract]
        [WebInvoke(UriTemplate = "Report/{key}", BodyStyle = WebMessageBodyStyle.Bare, Method="POST")]
        public void Rerport(string key, Stream value)
        {
             Report(key,GetStringFromStream(value));
        }

        private string GetStringFromStream(Stream content)
        {
    
            using(StreamReader reader = new StreamReader(content))
            {
              return reader.ReadToEnd();
            }
           
        }

    }
}
