
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



package hp.custom.java.activity;

public class Logger {

	public static Boolean LogDebug (String content)
	{
		return LogReportService.CallLogReportService("LogDebug",content);
	}
	public static Boolean LogError (String content)
	{
		return LogReportService.CallLogReportService("LogError",content);
	}
	public static Boolean LogInfo (String content)
	{
		return LogReportService.CallLogReportService("LogInfo",content);
	}

}
