
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------




package hp.custom.java.activity;

import java.io.InputStream;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.net.HttpURLConnection;
import java.net.URL;

public final class LogReportService {

	public static String  URL_PREFIX = "http://localhost:17266/LogReportService/";

	public static Boolean CallLogReportService(String methodName, String content) 
	{

	    HttpURLConnection urlc = null;
        OutputStream out = null;
        InputStream in = null;
			
		try{
			URL endpoint = new URL(URL_PREFIX + methodName);
			urlc = (HttpURLConnection) endpoint.openConnection();

			urlc.setRequestMethod("POST");
			urlc.setDoOutput(true);
			urlc.setDoInput(true);
			urlc.setUseCaches(false);
			urlc.setAllowUserInteraction(false);
			urlc.setRequestProperty("Content-type", "text/xml; charset=" + "UTF-8");


			out = urlc.getOutputStream();
			Writer writer = new OutputStreamWriter(out, "UTF-8");
			writer.write(content);
			writer.close();
			in = urlc.getInputStream();

			return true;
		}
		catch(Exception e)
		{
			return false;
		}
		finally{

			if (out != null)
				try {out.close();} catch (Exception e) {}
			if (in != null)
				try{in.close();} catch (Exception e) {}
			if (urlc != null)
				urlc.disconnect();
		}


	}


}
