
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------




package hp.custom.java.activity;

public class Properties {
	
	//Start of Generated Code


    // InputProperties Section
    public java.lang.String value;

    // OutputProperties Section

    // GeneralProperties Section
    public java.lang.String Name;


   //End of Generated Code
}
