
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



package hp.custom.java.activity;

public final class Reporter {

    public static Boolean Report (String key, String value)
	{
		return LogReportService.CallLogReportService("Report/"+key,value);
	}

}
