
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



package hp.custom.java.activity;

import hp.st.ext.java.ServiceTestCall;

import java.util.HashMap;

public class ServiceTestCallImpl implements ServiceTestCall {

	public HashMap<String, Object> execute(HashMap<String, Object> inputProperties) {
		
		HashMap<String, Object> outProps = new HashMap<String, Object>();
	
	
	    MyLogic logic = new MyLogic();
		//Start of Generated Code
        logic.Props.value = (java.lang.String)inputProperties.get("value");
        logic.Props.Name = (java.lang.String)inputProperties.get("Name");


		//End of Generated Code

		MyLogic.ExecutionResult result = logic.ExecuteLogic();
		
		outProps.put("ExecutionResult_E5F7897B-20DF-4E6F-9AB8-00519844ABA9",result.toString());


		//Start of Generated Code


		//End of Generated Code
		
				
		return outProps;
	}

	public HashMap<String, Class<?>> getInputProperties() {
		
		HashMap<String, Class<?>> props = new HashMap<String, Class<?>>();

		//Start of Generated Code
        props.put("value", java.lang.String.class);
        props.put("Name", java.lang.String.class);


		//End of Generated Code
		
		return props;
	}

	public HashMap<String, Class<?>> getOutputProperties() {
		
		HashMap<String, Class<?>> props = new HashMap<String, Class<?>>();
		
		props.put("ExecutionResult_E5F7897B-20DF-4E6F-9AB8-00519844ABA9", java.lang.String.class);

		//Start of Generated Code


		//End of Generated Code
		return props;
	}

}
        
        
